server:
  port: 8085

spring:
  application:
    name: api-service

  cloud:
    gateway:
      routes:
        - id: inventory
          uri: lb://inventory-service
          predicates:
            - Path=/tools/**
        - id: loan
          uri: lb://loan-service
          predicates:
            - Path=/loans/**
        - id: client
          uri: lb://client-service
          predicates:
            - Path=/api/v1/clients/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: report
          uri: lb://report-service
          predicates:
            - Path=/api/reports/**
        - id: fine
          uri: lb://fine-service
          predicates:
            - Path=/fines/**
      default-filters:
        - RemoveRequestHeader=Cookie
      httpclient:
        connect-timeout: 5000
        response-timeout: 5000

      # 👇 Configuración global de CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://192.168.59.107:30692"
            allowedMethods: "*"
            allowedHeaders: "*"

    loadbalancer:
      retry:
        enabled: true
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
