server:
  port: 0

spring:
  application:
    name: kardex-service
  datasource:
    url: jdbc:mysql://mysql-kardex:3306/kardexdb
    username: kardex
    password: kardex
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
