server:
  port: 0
spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:mysql://mysql-loan:3306/loandb
    username: loan
    password: loan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

