server:
  port: 0
spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/loandb
    username: martin
    password: martin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
