server:
  port: 0
spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:mysql://localhost:3306/loandb
    username: martin
    password: martin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
